package com.example.skindiagnosisai

import android.content.Context
import android.graphics.Bitmap
import android.util.Log // Import Log for debugging
import org.tensorflow.lite.Interpreter
import java.io.FileInputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.channels.FileChannel

class ModernTFLiteHelper(private val context: Context) {

    private lateinit var interpreter: Interpreter
    private val inputImageWidth = 224
    private val inputImageHeight = 224
    private val numberOfChannels = 3 // RGB
    // IMPORTANT: Make sure this order matches the 'class_names' generated by your Python script (e.g., sorted alphabetically)
    private val labels = listOf(
        "Berminyak",
        "Kering",
        "Normal"
    )

    companion object {
        private const val TAG = "ModernTFLiteHelper" // Tag for Logcat
    }

    fun loadModel() {
        try {
            val assetFileDescriptor = context.assets.openFd("gunawan_classifier_compatible.tflite")
            val fileInputStream = FileInputStream(assetFileDescriptor.fileDescriptor)
            val fileChannel = fileInputStream.channel
            val startOffset = assetFileDescriptor.startOffset
            val declaredLength = assetFileDescriptor.declaredLength
            val modelBuffer = fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength)

            interpreter = Interpreter(modelBuffer)
            Log.d(TAG, "Model loaded successfully.")
        } catch (e: Exception) {
            Log.e(TAG, "Error loading model: ${e.message}", e)
        }
    }

    fun classify(bitmap: Bitmap): String {
        if (!::interpreter.isInitialized) {
            Log.e(TAG, "Interpreter not initialized. Call loadModel() first.")
            return "Error: Model not loaded"
        }

        val resizedBitmap = Bitmap.createScaledBitmap(bitmap, inputImageWidth, inputImageHeight, true)
        Log.d(TAG, "Bitmap resized to ${resizedBitmap.width}x${resizedBitmap.height}")

        val inputBuffer = convertBitmapToByteBuffer(resizedBitmap)
        Log.d(TAG, "ByteBuffer created with capacity: ${inputBuffer.capacity()} bytes")

        val output = Array(1) { FloatArray(labels.size) }

        try {
            interpreter.run(inputBuffer, output)
            val resultProbabilities = output[0]

            Log.d(TAG, "Model Output Probabilities: ${resultProbabilities.joinToString()}")

            val maxProbability = resultProbabilities.maxOrNull()
            val maxIndex = resultProbabilities.indices.maxByOrNull { resultProbabilities[it] } ?: -1

            if (maxIndex != -1) {
                val predictedLabel = labels[maxIndex]
                Log.d(TAG, "Predicted Label: $predictedLabel with probability $maxProbability")
                return predictedLabel
            } else {
                Log.e(TAG, "Could not find max probability index.")
                return "Error: Classification failed"
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error running interpreter: ${e.message}", e)
            return "Error: Classification failed (${e.message})"
        }
    }

    private fun convertBitmapToByteBuffer(bitmap: Bitmap): ByteBuffer {
        val byteBuffer = ByteBuffer.allocateDirect(4 * inputImageWidth * inputImageHeight * numberOfChannels)
        byteBuffer.order(ByteOrder.nativeOrder())

        val pixels = IntArray(inputImageWidth * inputImageHeight)
        bitmap.getPixels(pixels, 0, bitmap.width, 0, 0, bitmap.width, bitmap.height)

        for (pixelValue in pixels) {
            val r = (pixelValue shr 16 and 0xFF).toFloat()
            val g = (pixelValue shr 8 and 0xFF).toFloat()
            val b = (pixelValue and 0xFF).toFloat()

            // THIS IS THE CRUCIAL CHANGE for MobileNetV2/V3 pre-trained on ImageNet
            // Normalization to [-1, 1]
            byteBuffer.putFloat((r / 127.5f) - 1.0f) // R
            byteBuffer.putFloat((g / 127.5f) - 1.0f) // G
            byteBuffer.putFloat((b / 127.5f) - 1.0f) // B
        }

        byteBuffer.rewind()
        return byteBuffer
    }

    fun close() {
        if (::interpreter.isInitialized) {
            interpreter.close()
            Log.d(TAG, "Interpreter closed.")
        }
    }
}